name: Frontend CI

on:
  push:
    branches:
      - dev
      - qa
      - uat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: npm ci

      - name: Build DEV
        if: github.ref_name == 'dev'
        run: npm run build:dev

      - name: Build QA
        if: github.ref_name == 'qa'
        run: npm run build:qa

      - name: Build UAT
        if: github.ref_name == 'uat'
        run: npm run build:uat